source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'VisualConstraints' do
  pod "VisualConstraints", :path => "../"
end

target 'Tests' do
  pod "VisualConstraints", :path => "../"

  pod 'FBSnapshotTestCase'
end
